name: "cdk-deploy-action"
description: "This action takes a single stack instance which was created through cdk synth and deploys it to a given account."
inputs:
  cdk-qualifier:
    description: "The cdk qualifier which was used during bootstrapping. Usually its the default value of 'hnb659fds'"
    required: true
    default: "hnb659fds"
  deploy-account-id:
    description: "The account id to deploy to"
    required: true
  deploy-region:
    description: "The region to deploy to"
    required: true
    default: "us-east-1"
  deploy-stack-name:
    description: "The stack name to deploy"
    required: true
  deploy-stack-as-name:
    description: "If this is defined the stack will be deployed with this name instead of the stack name"
    required: false
  deploy-role-arn:
    description: "The role arn to assume during deployment"
    required: true
  cdk-output-path:
    description: "The path containing the cdk output"
    required: true
    default: cdk.out
runs:
  using: "composite"
  steps:
    - name: assuming-deploy-account-role
      id: assume_deploy_account_role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.deploy-role-arn }}
        role-session-name: deploy
        aws-region: ${{ inputs.deploy-region }}
        output-credentials: true
    - name: upload stack assets
      shell: bash
      run: npx cdk-assets@2 --path ${{ inputs.cdk-output-path }}/${{ inputs.deploy-stack-name }}.assets.json --verbose publish
    - name: assuming cdk-deploy role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ steps.assume_deploy_account_role.outputs.aws-access-key-id }}
        aws-secret-access-key: ${{ steps.assume_deploy_account_role.outputs.aws-secret-access-key }}
        aws-session-token: ${{ steps.assume_deploy_account_role.outputs.aws-session-token }}
        role-to-assume: arn:aws:iam::${{ inputs.deploy-account-id }}:role/cdk-${{ inputs.cdk-qualifier }}-deploy-role-${{ inputs.deploy-account-id }}-${{ inputs.deploy-region }}
        role-session-name: cdk-deploy
        aws-region: ${{ inputs.deploy-region }}
        role-skip-session-tagging: true
    - name: deploy stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ inputs.deploy-stack-as-name || inputs.deploy-stack-name }}
        template: ${{ inputs.cdk-output-path }}/${{ inputs.deploy-stack-name }}.template.json
        role-arn: arn:aws:iam::${{ inputs.deploy-account-id }}:role/cdk-${{ inputs.cdk-qualifier }}-cfn-exec-role-${{ inputs.deploy-account-id }}-${{ inputs.deploy-region }}
